spring.application.name=FitnessTrackerApp

# DATABASE CONFIGURATION
spring.datasource.url=jdbc:postgresql://localhost:5433/goal_tracker
spring.datasource.username=postgres
spring.datasource.password=2000

spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / HIBERNATE CONFIG
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


# USDA FoodData Central API
usda.api.key=PNl62bEp5B3zU9fJOeV1CmkAdyHZ8rQvXjInLuswtT4cYD7oKM0GaqhSRFgWix
usda.api.base-url=https://api.nal.usda.gov/fdc/v1

# WGER API
wger.api.key=${WGER_API_KEY}
wger.api.base-url=https://wger.de/api/v2/

jwt.secret=6WIbcHaliVDtwhrcs9Gwl4i3I60dVChg/e75psdqJj+uVgThUS5+yVNp8ivYtOdxziyuUaB7l4lpQsXbAHOaUQ==

# ===============================
# SERVER PORT (optional)
# ===============================
server.port=8082